export const SEARCH_DEALS = 'DEALS/SEARCH_DEALS';
export const RESET_STATE = 'DEALS/RESET_STATE';
export const GET_DEAL_BY_ID = 'DEALS/GET_DEAL_BY_ID';
export const CREATE_DEAL = 'DEALS/CREATE_DEAL';
export const EDIT_DEAL = 'DEALS/EDIT_DEAL';
export const DELETE_DEAL = 'DEALS/DELETE_DEAL';
export const VERIFY_DEAL = 'DEALS/VERIFY_DEAL';
export const RECYCLE_DEAL = 'DEALS/RECYCLE_DEAL';

export const GET_DEAL_PICTURES = 'DEALS/GET_DEAL_PICTURES';
export const SAVE_DEAL_PICTURE = 'DEALS/SAVE_DEAL_PICTURE';

export const GET_DEAL_CATEGORIES = 'DEALS/GET_DEAL_CATEGORIES';
export const SAVE_DEAL_CATEGORIES = 'DEALS/SAVE_DEAL_CATEGORIES';

export const GET_CATEGORY_TREE = 'DEALS/GET_CATEGORY_TREE'
export const GET_CATEGORY_LIST = 'DEALS/GET_CATEGORY_LIST'

