export const SEARCH_BRANDS = 'BRAND/SEARCH_BRANDS';
export const GET_BRAND_BY_ID = 'BRANDS/GET_BRAND_BY_ID';
export const CREATE_BRAND = 'BRANDS/CREATE_BRAND';
export const UPDATE_BRAND = 'BRANDS/UPDATE_BRAND';