export const SEARCH_STORES = 'STORES/SEARCH_STORES';
export const GET_STORE_BY_ID = 'STORES/GET_STORE_BY_ID';
export const CREATE_STORE = 'STORES/CREATE_STORE';
export const UPDATE_STORE = 'STORES/UPDATE_STORE';
